# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
ur10_effort_ctrl: 

  joint:
    #proportional
    gains_p: [50, 612.71801, 612.71801, 150, 40, 5]
    
    #derivative
    gains_d: [100, 75, 75, 73, 15, 5]

    # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
    # Home: [0, -90, 0, -90, 0, 0] 
    # goal: [0, -90, 90, -90, 0, 0]
    # goal: [90, -90, 90, -90, 90, 0]
    goal: [90, -90, 0, -90, 0, 0,
           90, -90, 90, -90, 90, 0,
           0, -30, 30, -90, 90, 0]
    #  goal: [0, 0, 0, 0, 0, 0]
    time: 4.0

  cartesian:
    #proportional
    gains_p: [1, 1, 1, 3, 3, 1]
    
    #derivative
    gains_d: [100, 75, 75, 73, 15, 5]
