# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
ur10_effort_ctrl: 

  joint:
    #proportional
    gains_p: [50, 612.71801, 612.71801, 150, 40, 5]
    
    #derivative
    gains_d: [100, 75, 75, 73, 15, 5]

    # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
    # Home: [0, -90, 0, -90, 0, 0] 
    # goal: [0, -90, 90, -90, 0, 0]
    # goal: [90, -90, 90, -90, 90, 0]
    # goal: [90, -90, 0, -90, 0, 0,
    #        90, -90, 90, -90, 90, 0,
    #        0, -30, 30, -90, 90, 0]
    goal: [0, -150, -30, -90, -90, 0]
    #  goal: [0, 0, 0, 0, 0, 0]
    time: 4.0

    working_position: [-1.218, 0.164, 0.609]
    
  cartesian:
    #proportional
    gains_p: [1, 1, 1, 10, 8, 2]
    
    #derivative
    gains_d: [100, 75, 75, 73, 15, 5]

  tau_limits: [200, 150, 60, 50, 20, 50]